### ISSUE TITLE
Ime repozitorija

### ISSUE THREAD

**Issue by andrejbauer** [MarkoJerebFMF/Programiranje-2#8]
Sorry, da se šele zdaj pritožujem, ampak ime repozitorija `Programiranje-2` ni kaj preveč primerno. Kako pa nameravata poimenovati naslednji repozitorij, ko bosta delal 2. projekt? Bolje bi bilo, če bi bil repo poimenovan po igrici. Na GitHubu se da preimenovati repo, ampak prosim najprej preberita navodila.

**Comment by MarkoJerebFMF** [comment]
Opravljeno, nikoli ni prepozno dokler je še čas, da se popravi.
